name:                CsvUtf8
version:             0.1.0.0
github:              "githubuser/CsvUtf8"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/CsvUtf8#readme>

dependencies:
- base >= 4.7 && < 5
- text
- cassava
- vector
- bytestring
- utf8-string
- with-utf8

library:
  source-dirs: src

executables:
  CsvUtf8-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CsvUtf8

tests:
  CsvUtf8-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CsvUtf8
